Add more specific tracking of dominant speaker change events
jitsi/lib-jitsi-meet pull request #1582
Opened 2021-04-28 23:45 UTC by jbemmel

This patch adds tracking of { start, end, userId } for each dominant speaker change event, enabling richer conference statistics.

For example, see https://slack-files.com/T01U4KTU8TD-F02055Z3LG6-4ecd080671 - this type of meeting summary, showing the alternating participation of users, could be presented at the end of the conference (if enabled)

2021-04-28 23:54 UTC, jbemmel commented
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

Yes, I have done so in the context of the ongoing Hackathon. Let me know if you cannot find the doc - my name is Jeroen van Bemmel

2021-04-29 05:46 UTC, gjaekel commented
@jbemmel It will be **very** interesting for me to see how long it takes at the moment to get noticed and assigned to a maintainer to get approved and merged in.

2021-04-29 08:24 UTC, saghul requested changes
Left some comments, PTAL. Please check the GH action linter output, or run it locally with `npm run lint`.

In addition I think you'd like to modify https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_speakerstats_component.lua as well, since it's the "backend" for the data.

2021-04-29 08:24 UTC, saghul commented on modules/statistics/SpeakerStats.js
> +        var tsEntry;
Use let.

2021-04-29 08:24 UTC, saghul commented on modules/statistics/SpeakerStats.js
> +            // JvB: Track history of dominant speaker changes for the conference
Drop `JvB` it can get confusing here ;-)

2021-04-29 08:24 UTC, saghul commented on modules/statistics/SpeakerStats.js
> +        return tsEntry;
style: empty line before return

2021-04-29 08:24 UTC, saghul commented on modules/statistics/SpeakerStatsCollector.js
> +            speakerChanges: [], // JvB Array of { start, end, userId } speaker changes
ditto, remove JvB

2021-04-29 08:24 UTC, saghul commented on modules/statistics/SpeakerStatsCollector.js
> +            if (tsEvent) {
style: line after variable declarations

2021-04-29 08:24 UTC, saghul commented on modules/statistics/SpeakerStatsCollector.js
> +     * @private
It's not private.

2025-04-04 09:21 UTC, closed without merging