fix(recording): Send participant id when recording starts/stops
jitsi/lib-jitsi-meet pull request #1632
Opened 2021-06-08 11:52 UTC by vp8x8

This fixes the issue where undefined was sent instead of a participant on
recording stop/start. Appropriate handling has been done in jitsi-meet.

2021-06-08 14:22 UTC, damencho commented
@vp8x8 what is the point of the change? To be able to detect and when the local participant is doing the change?

2021-06-08 14:22 UTC, damencho requested changes
You also need to change the docs here https://github.com/jitsi/lib-jitsi-meet/blob/713db5d8c34a4a799cf33be7f4e1f5f99ed497c4/modules/recording/JibriSession.js#L127 that it is changed from participant to a jid ... 
And here https://github.com/jitsi/lib-jitsi-meet/blob/713db5d8c34a4a799cf33be7f4e1f5f99ed497c4/modules/recording/JibriSession.js#L119 and all docs around those initiator/terminator members of the class

2021-06-09 06:51 UTC, vp8x8 commented
> @vp8x8 what is the point of the change? To be able to detect and when the local participant is doing the change?

Yes exactly.

2021-06-09 11:48 UTC, damencho commented
Are you ready with the jitsi-meet part, maybe create yhe PR there first. If we metge this, we block updating jitsi-meet till you fix it ... As this is change in the API ... Oh now I wonder are there people using it already ... As we will break their code ...

2021-06-09 11:49 UTC, damencho commented
I will look around later to check how do we handle similar cases in other places ... Can we go wothout breaking the API ...

2021-06-09 12:02 UTC, vp8x8 commented
The PR is ready https://github.com/jitsi/jitsi-meet/pull/9362
Is there any other way to correlate the id with the participant? If there is I could maybe use it...

2021-06-09 12:23 UTC, damencho commented
> The PR is ready [jitsi/jitsi-meet#9362](https://github.com/jitsi/jitsi-meet/pull/9362)
> Is there any other way to correlate the id with the participant? If there is I could maybe use it...

Well we do not have JitsiParticipant object for the local participant. That is your problem right?

Other than that the participant id is part of the jid ... Is this what you mean?

2021-06-10 08:09 UTC, vp8x8 commented
I have updated the PR.

2021-06-10 18:38 UTC, damencho approved these changes

2021-06-10 18:44 UTC, merged