test: bump jasmine to 4.x to get ArrayBuffer equality matchers
jitsi/lib-jitsi-meet pull request #2068
Opened 2022-07-14 14:00 UTC by fippo

2022-07-14 14:49 UTC, saghul requested changes

2022-07-14 14:49 UTC, saghul commented on package.json
> +    "jasmine-core": "^4.2.0",
can you ping it to the exact version pl?

2022-07-14 14:49 UTC, saghul commented on package.json
> +    "karma-jasmine": "^4.0.2",
ditto

2022-07-14 15:29 UTC, NewEraCracker commented
Hello, while you are at it. Probably a good idea to update the following related packages - I have tested the following versions:

```
    "karma": "6.3.20",
    "karma-chrome-launcher": "3.1.1",
    "karma-jasmine": "5.0.1",
    "karma-sourcemap-loader": "0.3.8",
````

My two cents.

2022-07-14 19:08 UTC, fippo commented
leaving karma-jasmine at 4.x for now

2022-07-19 16:56 UTC, nils-ohlmeier approved these changes

2022-07-19 16:56 UTC, merged