fix: added better types
jitsi/lib-jitsi-meet pull request #2213
Opened 2023-02-07 17:50 UTC by vasav-prashar

2023-02-07 17:51 UTC, Parth0105 approved these changes

2023-02-08 18:58 UTC, Parth0105 submitted a review, later dismissed

2023-02-09 11:00 UTC, Parth0105 commented on service/authentication/AuthenticationEvents.spec.ts
> -    } = exported as any; // TODO: remove cast after typescript conversion
@hristoterezov  @saghul  @bgrozev can you please review this.

2023-02-09 12:21 UTC, saghul commented
Sorry, what are you fixing here? "other" is still unaccounted for.

2023-02-09 12:36 UTC, Parth0105 commented
> Sorry, what are you fixing here? "other" is still unaccounted for.

@saghul

2023-02-09 12:52 UTC, Parth0105 commented
> The whole point of that test is to make sure we don't miss any other exports. Maybe I'm missing something...

```
{
        IDENTITY_UPDATED: string,
        AuthenticationEvents: { IDENTITY_UPDATED: string },
} & { [key: string]: unknown }
``` i guess this would be a better type then taking into account any unneeded exports.?

2023-03-16 08:47 UTC, NewEraCracker requested changes
PTAL

2023-03-16 08:47 UTC, NewEraCracker commented on service/authentication/AuthenticationEvents.spec.ts
> +    } // TODO: remove cast after typescript conversion
```suggestion
    } & { [key: string]: unknown }
```

2023-03-16 11:58 UTC, vasav-prashar commented on service/authentication/AuthenticationEvents.spec.ts
> +    } // TODO: remove cast after typescript conversion
Done @NewEraCracker

2023-03-16 13:22 UTC, NewEraCracker approved these changes

2025-03-28 02:42 UTC, closed without merging