conference leave can block under certain circumstances
jitsi/lib-jitsi-meet pull request #2297
Opened 2023-06-19 04:13 UTC by luocongqiu

2023-06-19 04:39 UTC, luocongqiu commented
@jitsi-jenkins yes I sign a icla

2023-06-19 07:55 UTC, saghul requested changes
Please undo the first change, the second one is ok.

2023-06-19 07:55 UTC, saghul commented on JitsiConference.js
> +            .catch(() => {}); // eslint-disable-line no-empty-function
Why do you need this? It will break the logic below because onMemberLeft won't be called in that case.

2023-06-19 07:55 UTC, saghul commented on modules/xmpp/ChatRoom.js
> +                resolve();
This looks correct, good catch!

2023-08-17 09:59 UTC, saghul commented
Jenkins please test this please.

2023-09-12 20:48 UTC, saghul approved these changes

2023-09-12 20:49 UTC, saghul commented
Jenkins please test this please.

2023-09-12 21:05 UTC, saghul commented
Rebased in https://github.com/jitsi/lib-jitsi-meet/pull/2349

2023-09-12 21:05 UTC, closed without merging